### ISSUE TITLE
What is the data directory or directories used by steamcache?

### ISSUE THREAD

**Issue by JohanvdHoven** [steamcache/steamcache#13]
I am redirecting the data created by the steamcache docker (see my command line below).

sudo docker run --name steamcache --restart=always -d -v /srv/steamcache/data:/data/cache -v /srv/steamcache/logs:/data/logs -p 10.0.0.11:80:80 steamcache/steamcache:latest

Are the /data/cache and the /data/logs the only directories I have to redirect?
Can I just redirect /data to /srv/steamcache/data (or another directory on the computer running the cache) and get the same result?

**Comment by JasonRivers** [comment]
Sorry for the late response, Yes you can redirect /data, but be sure to create the 3 sub-directories ( cache, info, logs) as we don't check these currently.

**Comment by JohanvdHoven** [comment]
What is stored in the info sub-directory?

**Comment by JasonRivers** [comment]
The info directory is used when using the watchlog.sh script, to store a cached reference of the depot name, Currently we can only find out what the depot name is on steam, not the game name. We're writing our own API for steamdb to be able to work this information out easily and expose it to the image, at this point there will most likely be a sqlite database with these references in the info directory, this way we won't have to make a request to the API for every line in the logfile, we'll simple request once per depot, and cache the result.

IIRC this part of the watchlog.sh script is actually disabled as it currently uses steamdb site and you could end up with an IP Ban (on steamdb.info), the commented out lines in watchlog.sh can be used at your own risk until our system is in-place.
