### ISSUE TITLE
Ability to see cached items

### ISSUE THREAD

**Issue by barnabyc** [steamcache/steamcache#19]
Was wondering if it were possible to add a feature that could show names of cached items?

I've been running the docker container for a while and have amassed many gigs of cached files but have no way to know which games or applications those are for.

I'm happy to help contribute code to the project, just wondering if anything like a viewer is possible.

A follow-on enhancement would be to show human-readable game/application names when the cache is being read from (vs the quite verbose logging output that is accessible). Ie. _"Counter-Strike: GO - 4 clients reading - 13MiB/sec"_

Thanks for the project, hoping to help if possible!

**Comment by ilumos** [comment]
Hi Barnaby, the only free way to find out what is cached is to parse the logs using ELK. I've created a repo for this, but it's not compatible with this docker-based system out of the box, and is designed to be used with a bare-metal install of the cache:

https://github.com/zeropingheroes/lancache-elk

It will visualise what's in the cache by app ID, and which steam IDs have downloaded which app IDs.

If you want to see real-time speed statistics, you can use Luameter (paid):

https://luameter.com/demo

Hope this helps!

**Comment by barnabyc** [comment]
Thanks for the pointer @ilumos, excited to hear you've worked on something like this!

A related question, do you feel lancache is more preferable than steamcache if only Steam is being used? I noticed in the lancache readme that Steam doesn't handle corrupt files properly, so I assume steamcache is no better in that regard.

**Comment by ilumos** [comment]
In my testing, if Steam is served a corrupt file it can't use from the cache, it never sends the required cache-clearing HTTP request headers, so it doesn't matter whether nginx's `proxy_cache` or `try_files` is used (though `proxy_cache` does at least support purging corrupt files and requesting from upstream if Steam were ever to implement use of those headers)

I believe the `proxy_cache` method (steamcache/generic & zeropingheroes/lancache) is more performant and reliable, as it is designed for caching, and I'd always use it over `try_files` (steamcache/steamcache).

Hope this helps :)

**Comment by Copter64** [comment]
Has anyone deployed this in a multi-site enviroment?  We are trying to come up with a solution that will only be applied to one of our sites for now.  Possibly we will want to have a caching server for each site.  Anyone do this?

**Comment by JasonRivers** [comment]
@Copter64 This doesn't sound like it's related to this issue, Perhaps a new issue?

However, We commonly run a "master" cache on the internet which we populate our steamcache from (at least this used to be the case, I'm not sure if it is anymore), at the LAN we then set the upstream server to the server we have in the internet side, this allowed us to populate a new steamcache server for an event from the master server on the internet.

**Comment by VibroAxe** [comment]
Closed due to inactivity
