### ISSUE TITLE
DNS Forwarding

### ISSUE THREAD

**Issue by Copter64** [steamcache/steamcache#20]
I am looking into setting up the steam cache in a testing domain environment I am using.  I would need the ability to forward DNS traffic not handled by the Cache box to our DC's (Domain controllers).  Is that ability already there and I am missing it?

**Comment by GotenXiao** [comment]
This issue would be a better suited on the [steamcache-dns](https://github.com/steamcache/steamcache-dns) project.

That said, if you have domain controllers, another option would be to configure your DCs' DNS servers to use the steamcache-dns instance as an upstream forwarder, if you do not currently have any configured. This could be simpler in terms of deployment - your clients continue to use the DCs as primary DNS, but its answers for Steamcache addresses will be provided by steamcache-dns.
