### ISSUE TITLE
lls

### ISSUE THREAD

**Issue by Druidsnake** [steamcache/steamcache#21]
i followed the install of steamcache + steamcache-dns dockers and the cache works fine but when i try to navigate by  https, i got  403 forbidden error of nginx.  http works normally.
how i can solve this problem?

**Comment by Stealthii** [comment]
There is no support (or need of support) for https functionality in the cache - the only reason we can man-in-the-middle in the first place is the CDN servers that provide Steam (and other networks) are HTTP only.
