### ISSUE TITLE
Use Steamcache for complete game installations?

### ISSUE THREAD

**Issue by JohanvdHoven** [steamcache/steamcache#22]
I am going to attent a lanparty (12 persons) where we have to share a slow ADSL connection (6Mbit down at best).
Steamcache is running as a Docker service on an Ubuntu 16.04 installation on a I5-2500, 8GB, 2GB WD SATA harddrive.

    Can I "load" Steamcache with complete game installations by installing them through the Steamcache server on my fast internet connection at home (same IP settings)?
    Will the cached data expire after some time?
    Will the steamcache performance deteriorate when the amount of cached data increases?

**Comment by ilumos** [comment]
1. Yes, you can preload, use [`zeropingheroes/lancache-autofill`](https://github.com/zeropingheroes/lancache-autofill) or just delete the games from your Steam client and reinstall
2. In `steamcache/steamcache` the files do not expire, and in `steamcache/generic` they expire after 2 years
3. Not significantly. The bigger performance hit will come from several people downloading from the cache at the same time, causing the hard drive read head to seek all over the disk.

Hope this helps! :)

**Comment by JohanvdHoven** [comment]
Thank you! This is the info I was looking for ;-)
