### ISSUE TITLE
Use Steam Web API in watchlog.py instead of crawling steamdb

### ISSUE THREAD

**Issue by muffeeee** [steamcache/steamcache#23]
As a recommendation, you should translate steam app id's by using steam's own web API rather than requesting steamdb.info and crawling that page for the title of the depot. It's a cleaner approach, requires fewer overall requests and puts less strain on steamdb.

You can get a list of all steam games from this open steam API endpoint:
`https://api.steampowered.com/ISteamApps/GetAppList/v2/`

It has a much larger output (3.7MB) than steamdb (150KB), but you'll only have to download the applist once :)

**Comment by mintopia** [comment]
Hi muffeeee, unfortunately this wouldn't do all of what's required - we need a way to translate the depot ID to the app ID.

Open to ideas of how to fetch the app ID based on the depot in a reliable and guaranteed way. Whilst it's generally true that for depots 551 to 559 it will be appid 550 for instance, the same isn't true for other games with more depots.

**Comment by astrolox** [comment]
Closing this for now as the suggestion isn't workable as far as we know.
Please reopen if this proves to be incorrect.
