### ISSUE TITLE
How to set cache storage location

### ISSUE THREAD

**Issue by kanonfodda** [steamcache/steamcache#27]
Hi Guys, first up thanks for the images :)

I've just setup the images for steamcache and steamcache-DNS and they appear to be working.  However I want to change where the steamcache is putting it's cache.  The machine I'm using has an SSD for the OS (Ubuntu) and a 12TB raid 0 drive for the cache.

What is the best way to move the cache storage?  Is it easy to change the config within the docker image?

Regards

KF
LlamaLAN

**Comment by JasonRivers** [comment]
Hi @kanonfodda 

I'm not sure how you started your container, However, the best way to set the storage location is when you run the container, for instance running the following:

```docker run -d --name steamcache -p 192.168.0.5:80:80 -v /bigdata/cache:/data/cache -v /bigdata/logs:/data/logs steamcache/steamcache:latest```

Will result in the in the cache ending up in /bigdata/cache and the logs will be written to /bigdata/logs on the host system. 

I will update the readme to make this a little more clear when initially starting the container.

That said; it's possibly better to look at the [generic container](https://github.com/steamcache/generic) which does more than only steam (it does also do steam), and also for LlamaLAN it might be worth looking at the [steamcache-site-licence](https://github.com/steamcache/steamcache-site-license) which @mintopia has written. This allows Steam to use P2P when installing a game  in which it will use any other steam client on the network (as I understand it) which can also lower load on a central cache and it's also officially supported by Valve.

Jason

**Comment by kanonfodda** [comment]
Many thanks, figured it would be easy 😊 Ill take a look at the other containers too.

cheers for the quick response
