### ISSUE TITLE
New valve DNS domains

### ISSUE THREAD

**Issue by Candunc** [steamcache/steamcache#28]
Hello,

I noticed that my steam client was bypassing my steamcache, and I noticed these domains being used:

```
cdn2-sea1.valve.net - 205.196.6.153
cdn1-sea1.valve.net - 205.196.6.162
```

As these are not currently redirected as per the proxy, it skips steamcache entirely.

**Comment by Stealthii** [comment]
Awesome find, it's good to know about these things as soon as they pop up.

**Comment by mintopia** [comment]
Thanks for letting us know, I've updated the list in uklans/cache-domains which is where we're creating definitive lists for all services.
