### ISSUE TITLE
ran out of space in root 

### ISSUE THREAD

**Issue by randomaustralian** [steamcache/steamcache#34]
so I have left steamcache running idle for a couple of weeks to check its stability before I start to use it.

I have steamcache, steamcache-dns, steamcahe-generic and sniproxy running.

when I logged in steamcache and sniproxy had crashed out.  and wouldn't load again.

turned out I had put in the environment variables for data backward and it was caching to root instead of the hard drive I intended.

I have fixed my full drive and the environment variables but when I try to load the steamcache and generic version, they cant hold an IP address even though they are using different external IP addresses. Even loading only either one, they cant hold their IP address.

they are using the same interface with multiple IP addresses, but it didn't seem to be a problem a week ago... 

I'm lost for what to do here

**Comment by randomaustralian** [comment]
could I have permission issues with the directories I made for the containers?

**Comment by randomaustralian** [comment]
found the logs:
2018-07-10T03:54:07.070863000Z nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
2018-07-10T03:54:07.071328000Z nginx: [emerg] open() "/data/logs/access.log" failed (13: Permission denied)
2018-07-10T03:54:07.071659000Z nginx: configuration file /etc/nginx/nginx.conf test failed

i have tried ownership by root, nginx and dockerroot and none work

**Comment by Lepidopterist** [comment]
From memory, the UID and GID you need to set is the 'nginx' user in the container.  Outside of the container, this is *possibly* uid/gid 101

**Comment by JasonRivers** [comment]
We also have a test container in steamcache/steamcache:permissionfix which will sort the permissions out as part of the container startup. We haven't merged this change in yet as we didn't want to do this just before a LAN weekend.

**Comment by randomaustralian** [comment]
@Lepidopterist,  i had already tried manually setting permissions between nginx and dockerroot and setting permissions to 777. it made no difference.

i have since gotten it working... doesn't perform as well as i would have liked. but its running on mechanical drives so i'm sure that will slow it down a lot.
