### ISSUE TITLE
Cache only works, if you download the same thing from the same computer

### ISSUE THREAD

**Issue by RasmusKallas** [steamcache/steamcache#38]
Got the steamcache running, downloaded dota 2 on laptop, then downloaded started downloading it on desktop, but I still see speeds toward my normal (4-4.5MB/s by steam measuring), but if I deleted it on my laptop and redownloaded, I saw it install in few minutes (as it is supposed to), 2nd try on desktop worked aswell.
It seems like cache was for dota 2 machine spesific.
Repeated the experiment with unturned.

**Comment by JasonRivers** [comment]
This sounds like the second machine is not pointing to the cache, Please can you confirm that the DNS settings on both machines are pointing to the steamcache-dns container, and can you try running ```ping valve20.cs.steampowered.com``` and send the output

**Comment by VibroAxe** [comment]
Closing issue due to no reply
