### ISSUE TITLE
Slow initial download speeds

### ISSUE THREAD

**Issue by gelsas** [steamcache/steamcache#39]
Hello,

before using steamcache I had download speeds from 45-50MB/s .

Now with steamcache (run in docker) the initial download speed is at max 8-9 MB/s per second.

What could the issue be here?

**Comment by JasonRivers** [comment]
This will most likely be the hardware that you're running the steamcache on.  Without knowing what hardware you're running on or how you are running the containers we are unable to answer this fully.

**Comment by gelsas** [comment]
https://github.com/steamcache/generic/issues/45

Pleased take a look at this again, do you have the same issue If you are testing it with your Qnap?

**Comment by nexusofdoom** [comment]
Slow speeds? #15
two days ago was getting slow speed downloading, then last night I was getting about 110Mbps  vs the 30-40Mbps , note once it downloads the first time I can pull the update from the cache at 980mbps no issue to the client, it is just the first pull from steam is the issue. the server does not peek at any usage of cpu , memory , network or  drive.  it is like steams cdn was having issue or they are limiting how we pull down the updates.  my service from charter is 400Mbps / 20Mbps

**Comment by Ssupreme** [comment]
Hello, 

my ISP speed 100/100Mbps, download speed for one client (equipped with 1TB HDD) at a time around 10MB/s. Download speed for one client at a time over cache server around 3MB/s for first download, second download around 80MB/s. I don't see any bottlenecks on server side as it's dual 480GB SSD in raid0, i5-8600, 16GB, ASRock Fatal1ty Z370 Professional Gaming i7 with 10Gbps port to 10Gbps HPE switch. Clients connected over 1Gbps lines. The most interesting thing is that when I simultaneously run downloads on 3-4 clients for first time over cache server, I am getting around 10MB/s in total!
So server can handle higher total speed for more than one client, and each client can handle good hardware limit speed! Where is a bottleneck? I am not a linux guy, i think, there are could be some nginx/docker/other connection limits or speed limits. I am from middle europe, therefore I was thinking that cache server force to download from distant servers, as for example London is farther from me than Moscow or Warsaw. Any thoughts.

**Comment by VibroAxe** [comment]
So we've made a lot of progress on this in the last few days. If anyone would like to be involved in testing we would really appreciate your help. Please head over to https://github.com/steamcache/steamcache-dns/pull/69 and follow the instructions there

**Comment by VibroAxe** [comment]
https://github.com/steamcache/steamcache-dns/pull/69 is now merged and closed and should solve this problem.

Please note that steamcache/steamcache is now deprecated, we recommend moving to [steamcache/monolithic](https://hub.docker.com/r/steamcache/monolithic) instead
