### ISSUE TITLE
I am having a massive error 

### ISSUE THREAD

**Issue by 123hotdog1100** [steamcache/steamcache#40]
"docker: Error response from daemon: error while creating mount source path '/srv/steamcache/data': mkdir /srv/steamcache: read-only file system." is the error i get when ever i try and create a container for the steamcache i have no idea how to fix this error either

**Comment by 123hotdog1100** [comment]
yeh i tried using chmod but it didn't work

**Comment by webberist** [comment]
https://askubuntu.com/questions/197459/how-to-fix-sudo-unable-to-open-read-only-file-system
