### ISSUE TITLE
Steam can't load images/icons through Steamcache

### ISSUE THREAD

**Issue by c0deous** [steamcache/steamcache#41]
So I just got SteamCache setup using [this guide](https://arstechnica.com/gaming/2017/01/building-a-local-steam-caching-server-to-ease-the-bandwidth-blues/) and it's working great but came with an interesting side effect:

<img src="https://i.imgur.com/GycewtC.png"></img>
Game icons in my library are gone

<img src="https://i.imgur.com/LhvXQ5d.png"></img>
and the store page can't load 90% of the images it needs.

I tried loading the page in Firefox and got the same thing but managed to get the domain that these images are supposed to come from: `steamcdn-a.akamaihd.net`

I checked to see what IP that resolved to and it turned out to be my SteamCache server.

I'm pretty sure that it has to be a config issue but I literally just used the prebuilt images on a fresh install of docker and nobody else seems to be having the same trouble.

I'm going to remove the DNS zone for `steamcdn-a.akamaihd.net`.  Hopefully this doesn't break anything. Please let me know of any other fixes or if this is a bad idea.

**Comment by c0deous** [comment]
I managed to fix it by adding in this sketchy line to bootstrap.sh

    echo 'Implementing sketchboss fix'
    sed -i -e 's/zone "steamcdn-a.akamaihd.net"/##zone "steamcdn-a.akamaihd.net"/g' /etc/bind/cache.conf`

I added it right before the "finished bootstrapping" echo command and it seemed to do the trick.

Games are still caching properly (I think), if I have more issues I will report them here.

**Comment by JasonRivers** [comment]
Hi @c0deous If adding in the domain to the DNS container fixed the issue this sounds more like a DNS issue - the odd but here is without that domain in there it should have just bypassed the steamcache altogether.

If you have the latest version of the steamcache-dns container, we're now pulling the domains from https://github.com/uklans/cache-domains and we had a PR merged in for this domain here: https://github.com/uklans/cache-domains/pull/26

All you have to do with the latest image of the DNS container is restart it, it will auto-query uklans at startup and populate the DNS.

**Comment by c0deous** [comment]
Sorry, I worded my response kinda strange and you've got it backwards. I am using the latest version of steamcache-dns and it does come with the updated domain list from https://github.com/uklans/cache-domains which includes `steamcdn-a.akamaihd.net`.

The line that I added to `bootstrap.sh` actually comments out the zone line for the domain inside of `cache.conf` and that is what seemed to fix the issue: because the domain was being resolved to SteamCache and I disabled it.

**Comment by JasonRivers** [comment]
Thanks, I'll check this out. the domain should work through the cache,  but this may be a difference between steamcache and generic images.

**Comment by JasonRivers** [comment]
Hi @c0deous We're looking in to this, this appears to only be an issue with the steamcache image and doesn't happen in the generic image. I have just changed the config for the steamcache image, Would you be willing to give it a go? (I'm unable to test from the office).

If you could stop the steamcache container, and run it again using the image  ```steamcache/steamcache:domainfix``` (instead of latest) - If this works I will push my change to github.

Thanks.

**Comment by c0deous** [comment]
Yeah of course! I reset the steamcache-dns to resolve `steamcdn-a.akamaihd.net` and used `steamcache/steamcache:domainfix` but images still don't load.

I was just looking at the source url for one of the images:

`https://steamcdn-a.akamaihd.net/steam/spotlights/21af171b65ad547523fe4e24/spotlight_image_english.jpg?t=1535582674`

I think the problem is that images are served over SSL which means that even though it gets pointed at steamcache, there is not an available service on port 443 to handle it, so it just goes nowhere.

Is there an available config for SSL through NGINX?

**Comment by JasonRivers** [comment]
aha! right, in that case, run the SNIProxy on the same host as your steamcache. (I don't think it existed when the guide that you followed was created).
docker run -it -d -p 443:443 steamcache/sniproxy

This should solve the issue here.

**Comment by c0deous** [comment]
It worked!  That's what I get for not reading current documentation haha.

Thank you!

**Comment by jonirishlad** [comment]
Hi @JasonRivers, I'm pretty new to docker, but I've been able to make my through it for the most part.
However I'm stuck on the config of SNIProxy, I've deployed it, but it doesn't seem to be working.
Can you give anymore information regarding the config? Or is there a guide I can reference that goes more in depth?

thank you in advance!
