### ISSUE TITLE
Issue with synology NAS

### ISSUE THREAD

**Issue by Viking8** [steamcache/steamcache#42]
I was able to install steamcache and the dns part in DSM 6.2 and run the containers, but I found out that Synology does not let docker containers use port 80.  I found what I was hoping was a work around, but I am still not able to get caching to function. Here is the site with the workaround.....
http://tonylawrence.com/post/unix/synology/freeing-port-80/

Any help would be appreciated!

**Comment by harderthanfire** [comment]
If you ssh into the NAS and alter `/etc/nginx/nginx.conf` to not use port 80 then do `service nginx restart` you should be good to go.

I use steamcache on my synology NAS, I used the docker-compose for it rather than setting it up manually - after doing the above.

**Comment by Viking8** [comment]
> If you ssh into the NAS and alter `/etc/nginx/nginx.conf` to not use port 80 then do `service nginx restart` you should be good to go.
> 
> I use steamcache on my synology NAS, I used the docker-compose for it rather than setting it up manually - after doing the above.

Thank you so much for answering. I'm going to reset up my synology test computer and give that a whirl.
I'll let ya know how it goes! Take care.

**Comment by Viking8** [comment]
harderthanfire, 

I'm not familiar with docker compose. I was just going to install the docker application from the Synology package center and then use search for steamcache from within docker. 
Is docker compose better? If so, in what way(s) and how did you install it?

Thanks dude!

**Comment by Viking8** [comment]
harderthanfire,

I tried with all of my might to edit and have those edits stick in nginx.conf, but EVERYtime I edited the file and restarted nginx, it would revert back to using port 80. Synology REALLY doesn't want anyone changing that! By the way, I am testing with DSM 6.2 and service nginx restart doesn't work. I had to use synoservicecfg --restart nginx. Any more help you could offer would be very welcome!

Thanks.

**Comment by harderthanfire** [comment]
I'm running DSM 6.2-23739 Update 2 and it sticks for me. You are right about the restart command.

Make sure you do not have anything set on the NAS in DSM to use nginx as it might be overwriting the config. Make sure you edit using sudo. Failing that try the mustache file edits listed online. I had no luck with those myself.

If you do get the port clear you can use the docker compose script written by the steamcache folks from [here](https://github.com/steamcache/docker-compose). You will need to edit the .env file and create all the directories it needs but the DSM docker package already comes with docker compose so it is a simple sudo docker-compose up --build after that.

**Comment by VibroAxe** [comment]
Hi @harderthanfire @Viking8 you will need to run the steamcache on port 80 as thats what steam is expecting to connect to it on, there is no way to tell steam (via dns or otherwise) that a CDN is listening on anything other than port 80

Looking over here (https://www.synology.com/en-global/knowledgebase/DSM/tutorial/Network/What_network_ports_are_used_by_Synology_services) it looks like port 80 isn't used by the default management interface, are you running web/mail/photo station on your DSM?
