### ISSUE TITLE
GET latest version is cached for GuildWars 2 

### ISSUE THREAD

**Issue by 0x0017** [steamcache/steamcache#45]
logfile:
"GET /latest64/101 HTTP/1.1" 200 36 "-" "-" "HIT" "assetcdn.101.arenanetworks.com" "-"

this results in the client never getting a new version. this path should be excluded from the cache.
i am using ARENANETCACHE_IP with  steamcache/steamcache-dns

**Comment by JasonRivers** [comment]
Sorry for the long delay on this, we've all been rather busy of late, However, this isn't an issue with the steamcache image.

For DNS issues  Please report them over at https://github.com/uklans/cache-domains as the DNS container pulls all DNS information from that repository at startup.
