### ISSUE TITLE
Change proxy delay to 300s to fix slow downloading speed - but how?

### ISSUE THREAD

**Issue by AMDJona** [steamcache/steamcache#47]
Hey, I had a steamcache running about a year ago for a LAN event, it worked really well without affecting my downloadspeeds at all! Also redownloading worked with well over 60mb/s so I was very happy with it. Now I had to reinstall everything (Only Hardware change since then is upgrading from a 320gb HDD to a 512gb SSD since the old HDD died after 24/7 use)
But now if iam trying to download with my stemcache running my download speed is only 300-600kbs, without the cache it is sometimes more than 3x that speed.
I just read this issue : https://github.com/steamcache/steamcache/issues/44
Where they came to the conclusion that you have to change the proxy delay to 300s from the default of 60s, but I have no idea how to do this.
I'm running steamcache and the proxy inside docker containers but how do I change the nginx config in the docker container? Also is there any other way to improve download speeds? Like I said it's probably not a Hardware problem since it used to work with the same Hardware before.

oh yeah also Hardware just in case you need it:
SSD with 512 gb
8gb ddr3 
AMD Athlon 5350
Gigabit Ethernet, connected to a Gigabit Switch

**Comment by cr0x** [comment]
I'm facing the same issue. Were you able to solve it?

**Comment by wowdancing** [comment]
I think we need to wait for a reply from the developers. I have the same problem as well and made a post like this too.

**Comment by AMDJona** [comment]
Yeah, there is no real explanation

**Comment by nexusofdoom** [comment]
any update on this?

**Comment by AMDJona** [comment]
> any update on this?

I gave up, I had it running a year ago it worked sooo well, now it's just not working at all... I mean if you really have time to try, try using an older Linux version like Ubuntu 16 would prob. fix it

**Comment by GoTo1518** [comment]
I have same Problem, my Hardware likes the hardware on the first Post.
My Download pending from a few bits too no download too maximal 16Mbit.
I have tested alot of Hardware with Ubuntu 18.04.

![steam](https://user-images.githubusercontent.com/46189130/50474321-dac19000-09c0-11e9-8506-21cfc07f1e23.jpg)

**Comment by AMDJona** [comment]
> I have same Problem, my Hardware likes the hardware on the first Post.
> My Download pending from a few bits too no download too maximal 16Mbit.
> I have tested alot of Hardware with Ubuntu 18.04.
> 
> ![steam](https://user-images.githubusercontent.com/46189130/50474321-dac19000-09c0-11e9-8506-21cfc07f1e23.jpg)

Bro, I fixed it. I reinstalled my Ubuntu Server, but this time with Ubuntu 16.04 and guess what, it works with nearly 100% speed. No more speed loss while downloading, and when I download from the Cache I get +80mb/, with some games even full 112mb/s

**Comment by nexusofdoom** [comment]
I use this with ubuntu 18.04 
https://github.com/nexusofdoom/lancache-installer

only issue that I have is with steam , blizzard , origin all work at full speed just steam has a slow download speed.

**Comment by VibroAxe** [comment]
@nexusofdoom interesting that you are also seeing this issue as that particular installer uses bntjah's lancache not ours, this certainly implies steam have done something on their end...
Paging @mintopia for interest

**Comment by malteserr** [comment]
I can see that this issue is affecting many people right now, and I'm having the same problems with steam downloads (Origin downloads too from my admittedly very limited testing)

With regards to the suggestion of changing proxy delay to 300s, has anyone been able to figure out how this can be done on the container and are there any steps for beginners?

Thanks

**Comment by VibroAxe** [comment]
@malteserr the proxy delay you are talking about is referencing the delay before nginx terminates the upstream connection as a timeout and is unlikely to be related to this. We've never seen it have a visible effect. We are looking at where this issue is coming from, it currently looks most likely that steam have changed something on some of their CDN's

To answer @AMDJona "this is no longer functional" prospective, lancache has ALWAYS been designed to improve multiple repeat downloads not the initial download speed. In the case of a large lan, even if the download speed for an individual game is slowed (downloading multiple games is unaffected) the benefits to the other 30-3000 people on the network are still massive

**Comment by VibroAxe** [comment]
In an effort to track this down further we have a variant of the steamcache/generic image with this change in. I'd be grateful of any of you who would be able to do a side by side test with `steamcache/generic:proxy_read_timeout`

**Comment by fisheke** [comment]
Tried with the `steamcache/generic:proxy_read_timeout` image without any success. Downloading something new from Steam through the cache at 3/4 MBps where from the cache is at 80MBps.

Can't be the outside connection, as Origin is easily filling the cache at 20MBps.

Is there anything else I can try to diagnose the issue?

**Comment by VibroAxe** [comment]
So we've made a lot of progress on this in the last few days. If anyone would like to be involved in testing we would really appreciate your help. Please head over to https://github.com/steamcache/steamcache-dns/pull/69 and follow the instructions there

@fisheke @malteserr @AMDJona

**Comment by VibroAxe** [comment]
https://github.com/steamcache/steamcache-dns/pull/69 is now merged and closed and should solve this problem.

Please note that steamcache/steamcache is now deprecated, we recommend moving to [steamcache/monolithic](https://hub.docker.com/r/steamcache/monolithic) instead
