### ISSUE TITLE
Cached files not saving on network drive

### ISSUE THREAD

**Issue by ArkShocer** [steamcache/steamcache#48]
Just got the steamcache running successfully with a local drive as data folder, but when i changed it to an network share as data folder it didnt wanted to save the cached files to it (user has full access on the share i manually created/deleted files to check it)

**Comment by VibroAxe** [comment]
Are you using nfs, if so, it probably needs no_root_squash

**Comment by ArkShocer** [comment]
The windows share is a normal samba share and i tried it with your command above but it didnt worked - heres the command i use to map the drive in /etc/fstab `//Server.domain.example/share$ /media/scs cifs username=USER,password=PASSWORD,uid=nobody,iocharset=utf8 0 0`

**Comment by VibroAxe** [comment]
My guess is the internal docker users don't have proper access. This certainly isn't a recommended configuration, generally you don't want your cache files to be network mounted as it will massively reduce the speed your cache can run at.

However, in the interests of being helpful:
`docker exec -it steamcache sh` will get you into a docker shell, see if the www-data user is able to create files in /data/cache
