### ISSUE TITLE
Ability to see App ID

### ISSUE THREAD

**Issue by bobland1** [steamcache/steamcache#52]
Ive managed to set up Steamcache to an elk (elasticsearch, logstash, kibana). Only issue is its hard to see what actual games are stored on the steamcache drive. Is there a way i am able to either see an App ID instead of Depot Id or even see the game name

I followed this to make my steamcache-elk
https://github.com/steamcache/generic/issues/69

**Comment by VibroAxe** [comment]
Unfortunantly not, Some API's are available you might be able to link into, but nothing which would come from steamcache

**Comment by bobland1** [comment]
I would of thought steamcache to collect an app id log?

**Comment by ilumos** [comment]
Depots are not 1:1 mapped with apps.

One depot can be associated with many games, e.g. [depot 228986 for Visual C++ 2016](https://steamdb.info/depot/228986/apps/), used by 3,700 apps.
Also one app is typically comprised of several depots, e.g. [GTA V](https://steamdb.info/app/271590/depots/) is comprised of 7 depots.

**Comment by GotenXiao** [comment]
So I started working on some code way back in July 2018, according to my git log, to try to solve this particular problem. Dusted it off and will hopefully have something useful to show soon™.

Example output from the current test script:
```Single depot (framework):
{
  "depotID": 228986,
  "name": "VC 2015 Redist",
  "buildID": 3396060,
  "manifestID": 8782296191957115000,
  "lastManifestID": 8782296191957115000,
  "lastUpdated": "2019-04-22T16:53:37"
}

Single depot (game content), log name:
{
  "name": "440: Team Fortress 2 - TF2 Client server shared"
}

Single depot (framework), log name:
{
  "name": "VC 2015 Redist"
}

Single depot (game content), log details:
{
  "name": "TF2 Client server shared",
  "matches": [
    {
      "depotID": 441,
      "depotName": "TF2 Client server shared",
      "appID": 440,
      "appName": "Team Fortress 2"
    }
  ]
}
```
