### ISSUE TITLE
Not an Issue

### ISSUE THREAD

**Issue by Joly0** [steamcache/steamcache#53]
Hey, i just wanted to know, what is the difference, between steamcache:steamcache and steamcache:generic and when to use what?

**Comment by VibroAxe** [comment]
Steamcache/steamcache is one of our older legacy projects which attempts to maintain a mirror of certain steam files. Steamcache/generic is a much newer design implementing a proper cache engine compatible with multiple CDNs

Steamcache/monolithic is our new flagship product (based on the generic work) which we would suggest everybody migrates to, which enables caching of multiple downloaders within a single container.

Hope thats helpful

**Comment by Joly0** [comment]
Ok, and if i switch to monolithic, do i have to downlaod everything again, or are the cached files backwards-compatible with generic, if i used a volume?

**Comment by VibroAxe** [comment]
Unfortunately the cached files are not backwards compatible. Due to the way we handle the multiple content networks this has to be accounted for in the cache keys
