### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by nyemenzo** [steamcache/steamcache#54]
how can i update the location of cache? I run this command -v /cache/steam/data:/data/cache \
  -v /cache/steam/logs:/data/logs \ and wanted to update its location to /media/winshare/cache/steam/data:/data/cache and /media/winshare/cache/steam/logs:/data/logs \

thank you.

**Comment by VibroAxe** [comment]
First stop your docker container, then move the data
```
mkdir -p /media/winshare/cache/steam/
mv /cache/steam/data /media/winshare/cache/steam/data
mv /cache/steam/logs /media/winshare/cache/steam/logs
```
You will then need to delete and recreate the container with updated volume mapping
