### ISSUE TITLE
slower cached then from Steam

### ISSUE THREAD

**Issue by Padi1111** [steamcache/steamcache#55]
Hello guys I'm running in a small issue.
When games are not cached I download them at 25 MB/s.
When games are cached I'm only at ~10 MB/s but the server outputs ~100 MB/s.

![sans titre](https://user-images.githubusercontent.com/17253999/52892438-b600c200-3192-11e9-988d-af7adf91b66d.png)

**Comment by Padi1111** [comment]
I had to download the game 2 times before getting on the 3rd try a speed of 50 MB/s from the cache.
Is this normal ? Shouldn't it be downloading everything on the 1rst try and not also on the 2nd ?

**Comment by VibroAxe** [comment]
@Padi1111 Assuming you have just started with this container, I'd recommend looking at our monolithic project instead.

https://github.com/steamcache/steamcache-dns/pull/69 may also be of use to you when tuning uncached games

As for the speed test in your screenshot you are showing 100Mbit not MByte which is what steam measures in
