### ISSUE TITLE
Move to steamcache github organisation

### ISSUE THREAD

**Issue by astrolox** [steamcache/steamcache#6]
We need to move this repo over to the steamcache github organisation, and am thinking that move would probably be better than a new fork. I suspect that only Murray can do this.

**Comment by JasonDyalog** [comment]
Yep, Murray should be able to change the ownership, Once that's done and docker hub has been set up to reference the steamcache/steamcache repo, I'll remove my dockerhub image for it (It exists because Murrays is failing to build since we moved the Dockerfile).
