### ISSUE TITLE
Investigate possibility of populating cache from Steam backups

### ISSUE THREAD

**Issue by GotenXiao** [steamcache/steamcache#7]
Preliminary examination of the format contained in a Steam backup shows that it is formed of a series of archived depot chunks, complete with manifest files. It may therefore be possible to unpack a Steam backup into a format compatible with the cache.

**Comment by webberist** [comment]
I had a look at a steam backup for Factorio:
427521_depotcache_1.csd 249MB
It conly contains a single tiny file 'Z'.

Any hints as to how to extract the chunks?

**Comment by flazzarini** [comment]
I've tested the steamcache with Wolfenstein 3d which is a rather small game to download so ideal for testing. On the steamcache the download of Wolfentstein 3d created a folder with the id `2291` which corresponds roughly to the findings on this [page ](https://developer.valvesoftware.com/wiki/Steam_Application_IDs) where the id `2290` is listed. When I was doing a backup of the same game in steam it actually created the following files

* 2271_depotcache_1.csd
* 2271_depotcache_1.csm
* sku.sis

Where the `csd` file probably holds the game as it is the biggest.

I can't however find anything on the web to extract the files from the `csd` file. Any ideas on how to do this?

**Comment by ilumos** [comment]
To expand on GotenXiao's comment above:

When downloading a game from steam's content servers, first it downloads the manifests from e.g. `/depot/12345/manifest.json`  and then downloads the depot chunks from e.g. `/depot/12345/chunk/fbb12...`

Looks like the large `.csd` file is the depot chunks `tar`'d together and the small `.csm` file is the manifests.

Not sure about the `.sis` file.

**Comment by GotenXiao** [comment]
Examining the `.csd` in a text editor shows a ZIP file header, and upon extracting the `.csd` with 7zip, does show at least one file's contents, apparently unencrypted - I can open one of the DLLs from the game side by side, and it matches for the entire file, with an identical SHA-1. It's probable that the `.csm` contains a set of byte ranges for each file within the `.csd` file for Steam to restore the backup, but the on-disk format is thus likely to just be a series of zipped files concatenated.

However, this does make it less likely that the backups will be useful for populating a Steam cache, as the content on-disk on the cache is encrypted, and I have no desire to facilitate decrypting the content therein, or attempt re-encryption of a backup to rehost it via the cache.

For one, to do so would likely be a violation of the Steam terms of service (in spirit, even if not in fact), and second because if we wanted to do that we could simply host a fileshare containing backups of each title we were playing at a LAN. The seamless nature of using the Steam cache is its biggest asset as an event organiser.
Secondly, allowing re-encryption of content would then enable bad actors to utilise a Steam cache as an attack vector onto client machines.

I'm going to close this issue - thanks for your investigation of this, but I think it's safe to assume this avenue is no longer useful. I do hope to get back to improved methods of populating a cache shortly - I mentioned recently in another issue that there is a script we built using `steamcmd` that allows for the downloading of titles that your account is licensed to own.
