### ISSUE TITLE
watchlog.sh no output when downloading dota 2 updates

### ISSUE THREAD

**Issue by lynx29** [steamcache/steamcache#8]
I am testing this steamcache but not getting any output from watchlog.sh even already downloading dota 2 updates. I run both steamcache and steamcache dns on same server but if i open the ip address of of the server from local lan where the steamcache is running. I, got an error page coming from nginx server and there is log output on watchlog.sh but not when downloading dota 2 updates. btw newbie running docker.

**Comment by Robby12345** [comment]
Actually there is a bug in the config for the new cdn domain *.steampipe.steamcontent.com. 
See my PR https://github.com/steamcache/steamcache-dns/pull/5
You can use my fork from the repo https://github.com/Robby12345/steamcache-dns and build the docker image yourself with `docker build -t fixed-steamcache-dns steamcache-dns/`

**Comment by GotenXiao** [comment]
@Robby12345's PR has now been merged, and the Docker image on the hub has been updated. Give the updated DNS image a go (docker pull steamcache/steamcache-dns, then recreate your container) and see if that resolves your issue.
