### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by en3r0** [steamcache/steamcache#9]
I followed instructions on the latest Debian 8.6, but my connection on steam just times out. Can anyone confirm that the current script should still work correctly?

**Comment by dendryganarren** [comment]
I tested this a couple of days ago and it worked fine

**Comment by en3r0** [comment]
Thanks for the reply.

Can you think of what might be causing this issue? I can see the DNS is being hit, and other websites work just fine, but not steam downloads.

**Comment by en3r0** [comment]
I ended up resolving this by removing the images and starting over again. I may have gotten the command that auto gets the IP wrong.
